# Generated by Django 3.1 on 2020-08-12 17:18

import crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='expiration_time',
        ),
        migrations.RemoveField(
            model_name='device',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='device',
            name='power_state',
        ),
        migrations.RemoveField(
            model_name='device',
            name='registration_time',
        ),
        migrations.RemoveField(
            model_name='device',
            name='vmware_tool_state',
        ),
        migrations.RemoveField(
            model_name='person',
            name='address',
        ),
        migrations.RemoveField(
            model_name='person',
            name='expiration_time',
        ),
        migrations.RemoveField(
            model_name='person',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='person',
            name='registration_time',
        ),
        migrations.RemoveField(
            model_name='person',
            name='related_salesperson',
        ),
        migrations.RemoveField(
            model_name='person',
            name='tax_id',
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, max_length=63, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='device',
            name='uuid',
            field=models.CharField(default=crm.models.get_default_uuid, editable=False, max_length=63, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(blank=True, max_length=63, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(blank=True, max_length=63, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='person',
            name='remark',
            field=models.CharField(blank=True, max_length=255, verbose_name='Remark'),
        ),
        migrations.AlterField(
            model_name='person',
            name='uuid',
            field=models.CharField(default=crm.models.get_default_uuid, editable=False, max_length=63, verbose_name='UUID'),
        ),
    ]
